import {
  ShoppingCartIcon,
  ChatBubbleLeftRightIcon,
  ServerStackIcon,
  BuildingStorefrontIcon,
  UsersIcon,
  Square3Stack3DIcon,
  ClipboardDocumentListIcon,
  TruckIcon,
  CircleStackIcon,
  Squares2X2Icon,
  FunnelIcon,
  CalendarIcon,
  ChevronLeftIcon,
  PlayCircleIcon,
} from "@heroicons/react/24/outline";

export const Icons = {
  orders: ShoppingCartIcon,
  claims: ChatBubbleLeftRightIcon,
  repository: ServerStackIcon,
  distribution: BuildingStorefrontIcon,
  users: UsersIcon,
  roles: Square3Stack3DIcon,
  permissions: ClipboardDocumentListIcon,
  providers: TruckIcon,
  database: CircleStackIcon,
  squares: Squares2X2Icon,
  filter: FunnelIcon,
  calendar: CalendarIcon,
  chevronLeft: ChevronLeftIcon,
  playCircle: PlayCircleIcon,
};
